---
title: "Final Paper"
author: "Chelsea Marlborough"
date: "4/13/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(Hmisc)
library(ggplot2)
library(reshape)
library(AER)
library(grid)
library(plyr)
library(tidyverse)
library(dplyr)

```

```{r loading data, include=FALSE}

set.seed(13)
load("raw-data/spoils_of_victory_replication_data.RData")

options(warn = -1)

```

```{r heteroskedastically robust SE function, include=FALSE}

summaryR.lm <- function(model, type=c("hc3", "hc0", "hc1", "hc2", "hc4"), ...){
  if (!require(car)) stop("Required car package is missing.")
  type <- match.arg(type)
  V <- hccm(model, type=type)
  sumry <- summary(model)
  table <- coef(sumry)
  table[,2] <- sqrt(diag(V))
  table[,3] <- table[,1]/table[,2]
  table[,4] <- 2*pt(abs(table[,3]), df.residual(model), lower.tail=FALSE)
  sumry$coefficients <- table
  p <- nrow(table)
  hyp <- cbind(0, diag(p - 1))
  sumry
}

reais.format <- function(x){
  paste("R\\$", prettyNum(round(x), big.mark = ","), sep =" ")
}

```

```{r discontinuity function,include=FALSE}

discont.plot <- function(y, force.var, cluster, treat,  span = .7, n.boots = 100, bins = 25, xlab = "Forcing Variable", ylab = "Outcome", title="", degree = degree){
  data <- data.frame(y=y, force.var = force.var, cluster.id = cluster, treat = treat)
  clusters <- unique(cluster)
  for(i in 1:n.boots){
    bs.clusters <- data.frame(cluster.id=sample(clusters, replace=TRUE))
    bs.data <- merge(bs.clusters, data,all.x=TRUE,all.y=FALSE, by.x="cluster.id", by.y="cluster.id")
    lo.treat <- loess(y~force.var, data = bs.data[bs.data$treat==1,], span=span, surface="direct", degree = degree)
    lo.control <- loess(y~force.var, data = bs.data[bs.data$treat==0,], span=span, surface="direct", degree = degree)
    lo.fit.treat <- predict(lo.treat, newdata = data$force.var[data$treat==1])
    lo.fit.control <- predict(lo.control, newdata = data$force.var[data$treat==0])
    if(i ==1){
      lo.treat.bs <- matrix(nrow=length(lo.fit.treat), ncol = n.boots)
      lo.control.bs <- matrix(nrow=length(lo.fit.control), ncol = n.boots)
    }
    lo.treat.bs[,i] <- lo.fit.treat
    lo.control.bs[,i] <- lo.fit.control
    if( i %% (0.1 * n.boots) == 0) {  # output progress for each p
      cat(".")
    }
  }
  lo.treat <- loess(y~force.var, data = data[data$treat==1,], span=span, surface="direct", degree = degree)
  lo.control <- loess(y~force.var, data = data[data$treat==0,], span=span, surface="direct", degree = degree)
  lo.fit.treat <- predict(lo.treat, newdata = data$force.var[data$treat==1])
  lo.fit.control <- predict(lo.control, newdata = data$force.var[data$treat==0])
  lo.results.treat <- data.frame(force.var = data$force.var[data$treat==1], y = data$y[data$treat==1], y.fit = lo.fit.treat, conf.hi =  apply(lo.treat.bs,1,quantile,probs=c(.025)), conf.lo =  apply(lo.treat.bs,1,quantile,probs=c(.975)),treat=1)
  lo.results.treat$bin <- sapply(strsplit(gsub("^\\W|\\W$", "", cut(lo.results.treat$force.var, breaks = bins)), ","), function(x)sum(as.numeric(x))/2)
  lo.results.treat <- ddply(lo.results.treat, .(bin), transform, bin.mean = mean(y)) 
  lo.results.control <- data.frame(force.var = data$force.var[data$treat==0], y = data$y[data$treat==0], y.fit = lo.fit.control, conf.hi =  apply(lo.control.bs,1,quantile,probs=c(.025)), conf.lo =  apply(lo.control.bs,1,quantile,probs=c(.975)),treat=0)
  lo.results.control$bin <- sapply(strsplit(gsub("^\\W|\\W$", "", cut(lo.results.control$force.var, breaks = bins)), ","), function(x)sum(as.numeric(x))/2)
  lo.results.control <- ddply(lo.results.control, .(bin), transform, bin.mean = mean(y))
  lo.results <- rbind(lo.results.treat, lo.results.control)
  lo.results$treat <- as.factor(lo.results$treat)
  ggplot(lo.results, aes(x=force.var, y = y.fit, group=treat, color = treat)) + geom_line(aes(y=y.fit), size=1.5)  + geom_vline(xintercept=0) + geom_ribbon(aes(ymin = conf.hi, ymax=conf.lo), alpha =.2)  + geom_point(aes(x=bin, y=bin.mean)) + theme_bw()   + theme(legend.position = "none")  + scale_colour_brewer(palette="Set1")  + scale_x_continuous(xlab) +  scale_y_continuous(ylab) + labs(title = title) + theme(axis.title.x = element_text(vjust = .3)) + theme(plot.title = element_text(size = rel(.9)))
}

```

```{r loess estimating treatment effect function, include=FALSE}

boot.loess <- function(data, index, span = .75, degree = 2){
  boot.data <- data[index,]
  lo.treat <- loess(y~force.var, data = boot.data[boot.data$treat==1,], span=span, surface="direct", degree = degree)
  lo.cont <- loess(y~force.var, data = boot.data[boot.data$treat==0,], span=span, surface="direct", degree = degree)
  lo.fit.tr <- predict(lo.treat, newdata = 0, se = TRUE)
  lo.fit.co <- predict(lo.cont, newdata = 0, se = TRUE)
  c(lo.fit.tr$fit-lo.fit.co$fit, var.t = lo.fit.tr$se.fit + lo.fit.co$se.fit)
}

lo.ate <- function(y, treat, force.var, span = 1, R = 500, degree = 2, replicates = FALSE){
  library(boot)
  data <- data.frame(y, treat, force.var)
  boot.out <- boot(data = data, span = span, statistic = boot.loess, R  = R)
  ci.out <- boot.ci(boot.out, type = "stud")
  lo.treat <- loess(y~force.var, data = data[data$treat==1,], span=span, surface="direct", degree = degree)
  lo.cont <- loess(y~force.var, data = data[data$treat==0,], span=span, surface="direct", degree = degree)
  lo.fit.tr <- predict(lo.treat, newdata = 0)
  lo.fit.co <- predict(lo.cont, newdata = 0)
  if(replicates == TRUE){
    list(est = lo.fit.tr - lo.fit.co, se = sd(boot.out$t[,1]), conf.int = c(ci.out$student[4], ci.out$student[5]), tr.est = lo.fit.tr, con.est = lo.fit.co, boot.replicates = boot.out$t[,1])
  }
  else{
    list(est = lo.fit.tr - lo.fit.co, se = sd(boot.out$t[,1]), conf.int = c(ci.out$student[4], ci.out$student[5]), tr.est = lo.fit.tr, con.est = lo.fit.co)    
  }
}

```

```{r mccrary density test function, include=FALSE}

mccrary.test <- function(force.var, h = .75, n.boots = 1000){
  ##Note that this function assumes that the discontinuity is at 0
  force.below <-force.var[force.var<0]
  force.below <- force.below[force.below>=quantile(force.below, prob=.1)]
  force.above <-force.var[force.var>0]
  force.above <- force.above[force.above<=quantile(force.above, prob=.9)]
  bin.width <- 2 * sd(c(force.above,force.below)) * 1/sqrt(length(c(force.below,force.above)))
  force.below.bin <-  data.frame(table(cut(force.below, breaks = seq(0, min(force.below), by=-1*bin.width ))))
  force.above.bin <- data.frame(table(cut(force.above, breaks = seq(0, max(force.above), by=bin.width ))))
  force.below.bin$Var1 <- sapply(strsplit(gsub("^\\W|\\W$", "", force.below.bin$Var1), ","), function(x)sum(as.numeric(x))/2)
  force.above.bin$Var1 <- sapply(strsplit(gsub("^\\W|\\W$", "", force.above.bin$Var1), ","), function(x)sum(as.numeric(x))/2)
  bin.freq <- rbind(force.below.bin, force.above.bin)
  lo.fit.above <- loess(Freq~Var1, data = bin.freq[bin.freq$Var1>0,], degree=1,span = h)
  lo.fit.below <- loess(Freq~Var1, data = bin.freq[bin.freq$Var1<0,], degree=1,span = h)
  lo.predict <- rbind(data.frame(bin.mid = bin.freq$Var1[bin.freq$Var1<0],  pred.dens = predict(lo.fit.below)),data.frame(bin.mid = bin.freq$Var1[bin.freq$Var1>0],  pred.dens = predict(lo.fit.above)))
  wald.stat <- log(predict(loess(pred.dens~bin.mid, data=lo.predict[lo.predict$bin.mid<0,],span=h,degree=1, surface="direct") ,newdata=data.frame(bin.mid=0))) - log(predict(loess(pred.dens~bin.mid, data=lo.predict[lo.predict$bin.mid>0,],span=h,degree=1, surface="direct") ,newdata=data.frame(bin.mid=0)))
  
  #use the bootstrap to calculate standard error
  log.dis.bs <- matrix(nrow = n.boots)
  for(i in 1:n.boots){
    force.above.bs <- force.above[sample(1:length(force.above), replace = TRUE)]
    force.below.bs <- force.below[sample(1:length(force.below), replace = TRUE)]
    force.below.bs <- force.below.bs[force.below.bs>=quantile(force.below.bs, prob=.1)]
    force.above.bs <- force.above.bs[force.above.bs<=quantile(force.above.bs, prob=.9)]
    bin.width <- 2 * sd(c(force.above.bs,force.below.bs)) * 1/sqrt(length(c(force.below.bs, force.above.bs)))
    force.below.bin <-  data.frame(table(cut(force.below.bs, breaks = seq(0, min(force.below.bs), by=-1*bin.width ))))
    force.above.bin <- data.frame(table(cut(force.above.bs, breaks = seq(0, max(force.above.bs), by=bin.width ))))
    force.below.bin$Var1 <- sapply(strsplit(gsub("^\\W|\\W$", "", force.below.bin$Var1), ","), function(x)sum(as.numeric(x))/2)
    force.above.bin$Var1 <- sapply(strsplit(gsub("^\\W|\\W$", "", force.above.bin$Var1), ","), function(x)sum(as.numeric(x))/2)
    bin.freq <- rbind(force.below.bin, force.above.bin)
    lo.fit.above <- loess(Freq~Var1, data = bin.freq[bin.freq$Var1>0,], degree=1,span = h)
    lo.fit.below <- loess(Freq~Var1, data = bin.freq[bin.freq$Var1<0,], degree=1,span = h)
    lo.predict <- rbind(data.frame(bin.mid = bin.freq$Var1[bin.freq$Var1<0],  pred.dens = predict(lo.fit.below)),data.frame(bin.mid = bin.freq$Var1[bin.freq$Var1>0],  pred.dens = predict(lo.fit.above)))
    
    log.dis.bs[i] <- log(predict(loess(pred.dens~bin.mid, data=lo.predict[lo.predict$bin.mid<0,],span=h,degree=1, surface="direct") ,newdata=data.frame(bin.mid=0))) - log(predict(loess(pred.dens~bin.mid, data=lo.predict[lo.predict$bin.mid>0,],span=h,degree=1, surface="direct") ,newdata=data.frame(bin.mid=0)))
  }
  list(wald.stat = wald.stat, se = sd(log.dis.bs, na.rm = TRUE))  
}

```

```{r number of bootstrap samples, include=FALSE}

num.boots <- 1000

```

```{r parameters for loess estimator, include=FALSE}

span <- 1
lo.degree <- 1

```

```{r datasets of varioius samples, include=FALSE}

depfed_data$incumbent <- depfed.balance$incumbent
depfed_data$uf.sp <- ifelse(depfed_data$uf == "SP", 1, 0)
depfed_data$uf.mg <- ifelse(depfed_data$uf == "MG", 1, 0)
##Loess Data, Estimation Samples
lo.bw <- 40000
lo.all.data <- depfed_data[abs(depfed_data$votemargin)<lo.bw & depfed_data$donations>0,]
lo.all.pw.data <- depfed_data[abs(depfed_data$votemargin)<lo.bw & depfed_data$pw.donations>0,]
lo.coal.pw.data <- depfed_data[abs(depfed_data$votemargin)<lo.bw & depfed_data$pw.donations>0 & depfed_data$party %in% c('PMDB','PP','PV','PSB','PC do B','PDT','PL','PRONA'),]
lo.pt.pw.data <- depfed_data[abs(depfed_data$votemargin)<lo.bw & depfed_data$pw.donations>0 & depfed_data$party == "PT",]

```

```{r loess balance samples, include=FALSE}

lo.all.baldata <- depfed.balance[abs(depfed.balance$votemargin)<lo.bw & depfed.balance$donations>0,]
lo.all.pw.baldata <- depfed.balance[abs(depfed.balance$votemargin)<lo.bw & depfed.balance$pw.donations>0,]
lo.coal.pw.baldata <- depfed.balance[abs(depfed.balance$votemargin)<lo.bw & depfed.balance$pw.donations>0 & depfed.balance$party %in% c('PMDB','PP','PV','PSB','PC do B','PDT','PL','PRONA'),]
lo.pt.pw.baldata <- depfed.balance[abs(depfed.balance$votemargin)<lo.bw & depfed.balance$pw.donations>0 & depfed.balance$party == "PT",]

```

```{r local linear bindwith, include=FALSE}

ll.bw <- 25000
##Local Linear Data, Estimation Samples
ll.all.data <- depfed_data[abs(depfed_data$votemargin) < ll.bw & depfed_data$donations > 0,]
ll.all.pw.data <- depfed_data[abs(depfed_data$votemargin)<ll.bw & depfed_data$pw.donations>0,]
ll.coal.pw.data <- depfed_data[abs(depfed_data$votemargin)<ll.bw & depfed_data$pw.donations>0 & depfed_data$party %in% c('PMDB','PP','PV','PSB','PC do B','PDT','PL','PRONA'),]
ll.pt.pw.data <- depfed_data[abs(depfed_data$votemargin)<ll.bw & depfed_data$pw.donations>0 & depfed_data$party == "PT",]

```

```{r local linear data balance samples, include=FALSE}

ll.all.baldata <- depfed.balance[abs(depfed.balance$votemargin) < ll.bw & depfed.balance$donations > 0,]
ll.all.pw.baldata <- depfed.balance[abs(depfed.balance$votemargin)<ll.bw & depfed.balance$pw.donations>0,]
ll.coal.pw.baldata <- depfed.balance[abs(depfed.balance$votemargin)<ll.bw & depfed.balance$pw.donations>0 & depfed.balance$party %in% c('PMDB','PP','PV','PSB','PC do B','PDT','PL','PRONA'),]
ll.pt.pw.baldata <- depfed.balance[abs(depfed.balance$votemargin)<ll.bw & depfed.balance$pw.donations>0 & depfed.balance$party == "PT",]

```

```{r polynomial data estimation samples, include=FALSE}

poly.order <- 3
ply.bw <- 100000
ply.all.data <- depfed_data[abs(depfed_data$votemargin) < ply.bw & depfed_data$donations > 0,]
ply.all.pw.data <- depfed_data[abs(depfed_data$votemargin) < ply.bw & depfed_data$pw.donations>0,]
ply.coal.pw.data <- depfed_data[abs(depfed_data$votemargin) < ply.bw & depfed_data$pw.donations>0 & depfed_data$party %in% c('PMDB','PP','PV','PSB','PC do B','PDT','PL','PRONA'),]
ply.pt.pw.data <- depfed_data[abs(depfed_data$votemargin) < ply.bw & depfed_data$pw.donations>0 & depfed_data$party == "PT",]

```

```{r polynomial data balance samples, include=FALSE}

ply.all.baldata <- depfed.balance[abs(depfed.balance$votemargin) < ply.bw & depfed.balance$donations > 0,]
ply.all.pw.baldata <- depfed.balance[abs(depfed.balance$votemargin) < ply.bw & depfed.balance$pw.donations>0,]
ply.coal.pw.baldata <- depfed.balance[abs(depfed.balance$votemargin) < ply.bw & depfed.balance$pw.donations>0 & depfed.balance$party %in% c('PMDB','PP','PV','PSB','PC do B','PDT','PL','PRONA'),]
ply.pt.pw.baldata <- depfed.balance[abs(depfed.balance$votemargin) < ply.bw & depfed.balance$pw.donations>0 & depfed.balance$party == "PT",]

```

```{r fig 1 balance tests}

bal.var <- c("coalvotes", "incumbent", "contracts.0406", "pw.con.0406", "donations", "pw.donations", "donor.firms", "pw.donor.firms", "year.opened", "commerce", "manufacture", "financial", "cand.uf.sp", "cand.uf.mg", "cand.uf.rs", "cand.uf.ba", "cand.uf.rj", "party.psdb", "party.pfl", "party.pt", "party.pmdb", "superior.edu", "occ.pol", "yob", "individ.donations", "occ.business", "coalvotes", "individual.donors", "coalseats", "agriculture", "numb.company.recipients", "total.company.donations", "totalDonations.winners.firm", "winners.donated.to")


lo.bal <- list()
lo.bal$all <- list()
lo.bal$all.pw <- list()
lo.bal$coal.pw <- list()
lo.bal$pt.pw <- list()

ll.bal <- list()
ll.bal$all <- list()
ll.bal$all.pw <- list()
ll.bal$coal.pw <- list()
ll.bal$pt.pw <- list()
length(ll.bal$pt.pw) <- length(bal.var)

ply.bal <- list()
ply.bal$all <- list()
ply.bal$all.pw <- list()
ply.bal$coal.pw <- list()
ply.bal$pt.pw <- list()
length(ply.bal$pt.pw) <- length(bal.var)

for(i in 1:length(bal.var)){
  print(paste("Checking Balance on", bal.var[i]))
  lo.bal$all[[i]] <- with(lo.all.baldata, lo.ate(y = lo.all.baldata[ , bal.var[i]], treat = elected, force.var = votemargin, span = span, R = num.boots, degree = lo.degree))
  lo.bal$all[[i]]$sd <- (sd(lo.all.baldata[lo.all.baldata$elected == 1 , bal.var[i]]) + sd(lo.all.baldata[lo.all.baldata$elected == 0 , bal.var[i]])) / 2
  names(lo.bal$all)[i] <- bal.var[i]
  
  lo.bal$all.pw[[i]] <- with(lo.all.pw.baldata, lo.ate(y = lo.all.pw.baldata[, bal.var[i]], treat = elected, force.var = votemargin, span = span, R = num.boots, degree = lo.degree))
  lo.bal$all.pw[[i]]$sd <- (sd(lo.all.pw.baldata[lo.all.pw.baldata$elected == 1 , bal.var[i]]) + sd(lo.all.pw.baldata[lo.all.pw.baldata$elected == 0 , bal.var[i]])) / 2
  names(lo.bal$all.pw)[i] <- bal.var[i]
  
  if(length(unique(lo.coal.pw.baldata[ , bal.var[i]])) == 1){
    lo.bal$coal.pw[[i]] <- NA
  }
  if(length(unique(lo.coal.pw.baldata[ , bal.var[i]])) > 1){
    lo.bal$coal.pw[[i]] <- with(lo.coal.pw.baldata, lo.ate(y = lo.coal.pw.baldata[, bal.var[i]], treat = elected, force.var = votemargin, span = span, R = num.boots, degree = lo.degree))
    lo.bal$coal.pw[[i]]$sd <- (sd(lo.coal.pw.baldata[lo.coal.pw.baldata$elected == 1 , bal.var[i]]) + sd(lo.coal.pw.baldata[lo.coal.pw.baldata$elected == 0 , bal.var[i]])) / 2  
  }
  names(lo.bal$coal.pw)[i] <- bal.var[i]
  
  if(length(unique(lo.pt.pw.baldata[ , bal.var[i]])) == 1){
    lo.bal$pt.pw[[i]] <- NA
  }
  if(length(unique(lo.pt.pw.baldata[ , bal.var[i]])) > 1){
    lo.bal$pt.pw[[i]] <- with(lo.pt.pw.baldata, lo.ate(y = lo.pt.pw.baldata[, bal.var[i]], treat = elected, force.var = votemargin, span = span, R = num.boots, degree = lo.degree))
    lo.bal$pt.pw[[i]]$sd <- (sd(lo.pt.pw.baldata[lo.pt.pw.baldata$elected == 1 , bal.var[i]]) + sd(lo.pt.pw.baldata[lo.pt.pw.baldata$elected == 0 , bal.var[i]])) / 2
  }
  names(lo.bal$pt.pw)[i] <- bal.var[i]
  
  ll.bal$all[[i]] <- summaryR.lm(lm(formula(paste(bal.var[i], "~ elected*votemargin")) , data = ll.all.baldata), type = "hc2")
  ll.bal$all[[i]]$sd <- (sd(ll.all.baldata[ll.all.baldata$elected == 1, bal.var[i]]) + sd(ll.all.baldata[ll.all.baldata$elected == 0, bal.var[i]])) / 2
  names(ll.bal$all)[i] <- bal.var[i]
  
  ll.bal$all.pw[[i]] <- summaryR.lm(lm(formula(paste(bal.var[i], "~ elected*votemargin")) , data = ll.all.pw.baldata), type = "hc2")
  ll.bal$all.pw[[i]]$sd <- (sd(ll.all.pw.baldata[ll.all.pw.baldata$elected == 1, bal.var[i]]) + sd(ll.all.pw.baldata[ll.all.pw.baldata$elected == 0, bal.var[i]])) / 2
  names(ll.bal$all.pw)[i] <- bal.var[i]
  
  if(length(unique(ll.coal.pw.baldata[ , bal.var[i]])) == 1){
    ll.bal$coal.pw[[i]] <- NA
  }
  if(length(unique(ll.coal.pw.baldata[ , bal.var[i]])) > 1){
    ll.bal$coal.pw[[i]] <- summaryR.lm(lm(formula(paste(bal.var[i], "~ elected*votemargin")) , data = ll.coal.pw.baldata), type = "hc2")
    ll.bal$coal.pw[[i]]$sd <- (sd(ll.coal.pw.baldata[ll.coal.pw.baldata$elected == 1, bal.var[i]]) + sd(ll.coal.pw.baldata[ll.coal.pw.baldata$elected == 0, bal.var[i]])) / 2
  }
  names(ll.bal$coal.pw)[i] <- bal.var[i]
  
  if(length(unique(ll.pt.pw.baldata[ , bal.var[i]])) == 1){
    ll.bal$pt.pw[[i]] <- NA
  }
  if(length(unique(ll.pt.pw.baldata[ , bal.var[i]])) > 1){
    ll.bal$pt.pw[[i]] <- tryCatch(summaryR.lm(lm(formula(paste(bal.var[i], "~ elected*votemargin")) , data = ll.pt.pw.baldata), type = "hc2"), error = function(e) NA)
    if(is.na(ll.bal$pt.pw[[i]][1]) == FALSE){
      ll.bal$pt.pw[[i]]$sd <- (sd(ll.pt.pw.baldata[ll.pt.pw.baldata$elected == 1, bal.var[i]]) + sd(ll.pt.pw.baldata[ll.pt.pw.baldata$elected == 0, bal.var[i]])) / 2
    }
  }
  names(ll.bal$pt.pw)[i] <- bal.var[i]  
  ply.bal$all[[i]] <- summaryR.lm(lm(formula(paste(bal.var[i], "~ elected * votemargin + ", paste("I(votemargin^", 2:poly.order, ") * elected", sep ="", collapse = " + "))) , data = ply.all.baldata), type = "hc2")
  ply.bal$all[[i]]$sd <- (sd(ply.all.baldata[ply.all.baldata$elected == 1, bal.var[i]]) + sd(ply.all.baldata[ply.all.baldata$elected == 0, bal.var[i]])) / 2
  names(ply.bal$all)[i] <- bal.var[i]
  
  ply.bal$all.pw[[i]] <- summaryR.lm(lm(formula(paste(bal.var[i], "~ elected * votemargin + ", paste("I(votemargin^", 2:poly.order, ") * elected", sep ="", collapse = " + "))) , data = ply.all.pw.baldata), type = "hc2")
  ply.bal$all.pw[[i]]$sd <- (sd(ply.all.pw.baldata[ply.all.pw.baldata$elected == 1, bal.var[i]]) + sd(ply.all.pw.baldata[ply.all.pw.baldata$elected == 0, bal.var[i]])) / 2
  names(ply.bal$all.pw)[i] <- bal.var[i]
  
  if(length(unique(ply.coal.pw.baldata[ , bal.var[i]])) == 1){
    ply.bal$coal.pw[[i]] <- NA
  }
  if(length(unique(ply.coal.pw.baldata[ , bal.var[i]])) > 1){
    ply.bal$coal.pw[[i]] <- summaryR.lm(lm(formula(paste(bal.var[i], "~ elected * votemargin + ", paste("I(votemargin^", 2:poly.order, ") * elected", sep ="", collapse = " + "))) , data = ply.coal.pw.baldata), type = "hc2")
    ply.bal$coal.pw[[i]]$sd <- (sd(ply.coal.pw.baldata[ply.coal.pw.baldata$elected == 1, bal.var[i]]) + sd(ply.coal.pw.baldata[ply.coal.pw.baldata$elected == 0, bal.var[i]])) / 2
  }
  names(ply.bal$coal.pw)[i] <- bal.var[i]
  
  if(length(unique(ply.pt.pw.baldata[ , bal.var[i]])) == 1){
    ply.bal$pt.pw[[i]] <- NA
  }
  if(length(unique(ply.pt.pw.baldata[ , bal.var[i]])) > 1){
    ply.bal$pt.pw[[i]] <- tryCatch(summaryR.lm(lm(formula(paste(bal.var[i], "~ elected * votemargin + ", paste("I(votemargin^", 2:poly.order, ") * elected", sep ="", collapse = " + "))) , data = ply.pt.pw.baldata), type = "hc2"), error = function(e) NA)
    if(is.na(ply.bal$pt.pw[[i]][1]) == FALSE){
      ply.bal$pt.pw[[i]]$sd <- (sd(ply.pt.pw.baldata[ply.pt.pw.baldata$elected == 1, bal.var[i]]) + sd(ply.pt.pw.baldata[ply.pt.pw.baldata$elected == 0, bal.var[i]])) / 2
    }
  }
  names(ply.bal$pt.pw)[i] <- bal.var[i]
  
}

lo.bal <- lapply(lo.bal, function(x){x[is.na(x)] <- NULL; x})
ll.bal <- lapply(ll.bal, function(x){x[is.na(x)] <- NULL; x})
ply.bal <- lapply(ply.bal, function(x){x[is.na(x)] <- NULL; x})
std.diff.table <- data.frame(Estimate = c(
  ldply(lo.bal, function(x) ldply(x, function(x) x$est))$V1,
  ldply(ply.bal, function(x) ldply(x, function(x) coef(x)[2,1]))$V1,
  ldply(ll.bal, function(x) ldply(x, function(x) coef(x)[2,1]))$V1),
                             SD = c(
                               ldply(lo.bal, function(x) ldply(x, function(x) x$sd))$V1,
                               ldply(ply.bal, function(x) ldply(x, function(x) x$sd))$V1,
                               ldply(ll.bal, function(x) ldply(x, function(x) x$sd))$V1),
                             Variable = c(
                               ldply(lo.bal, function(x) ldply(x, function(x) x$sd))$.id,
                               ldply(ply.bal, function(x) ldply(x, function(x) x$sd))$.id,
                               ldply(ll.bal, function(x) ldply(x, function(x) x$sd))$.id),  
                             Sample = c(rep(c("All", "Public Works", "Public Works, Coalition", "Public Works, PT"), sapply(lo.bal, length)), 
                                        rep(c("All", "Public Works", "Public Works, Coalition", "Public Works, PT"), 
                                            sapply(ply.bal, length)),
                                        rep(c("All", "Public Works", "Public Works, Coalition", "Public Works, PT"), sapply(ll.bal, length))
                             ),
                             Estimator = c(
                               rep("Loess", sum(sapply(lo.bal, length))), 
                               rep("Polynomial", sum(sapply(ply.bal, length))), rep("Local Linear", sum(sapply(ll.bal, length))))
)
std.diff.table$std.diff <- std.diff.table$Estimate / std.diff.table$SD
std.diff.table$Variable <- reorder(std.diff.table$Variable, std.diff.table$std.diff, mean)

tstat.table <- data.frame(Estimate = c(
  ldply(lo.bal, function(x) ldply(x, function(x) x$est))$V1,
  ldply(ply.bal, function(x) ldply(x, function(x) coef(x)[2,1]))$V1,
  ldply(ll.bal, function(x) ldply(x, function(x) coef(x)[2,1]))$V1),
                          SE = c(
                            ldply(lo.bal, function(x) ldply(x, function(x) x$se))$V1,
                            ldply(ply.bal, function(x) ldply(x, function(x) coef(x)[2,2]))$V1,
                            ldply(ll.bal, function(x) ldply(x, function(x) coef(x)[2,2]))$V1),
                          Variable = c(
                            ldply(lo.bal, function(x) ldply(x, function(x) x$sd))$.id,
                            ldply(ply.bal, function(x) ldply(x, function(x) x$sd))$.id,
                            ldply(ll.bal, function(x) ldply(x, function(x) x$sd))$.id),  
                          Sample = c(
                            rep(c("All", "Public Works", "Public Works, Coalition", "Public Works, PT"), sapply(lo.bal, length)), 
                            rep(c("All", "Public Works", "Public Works, Coalition", "Public Works, PT"), sapply(ply.bal, length)),
                            rep(c("All", "Public Works", "Public Works, Coalition", "Public Works, PT"), sapply(ll.bal, length))
                          ),
                          Estimator = c(
                            rep("Loess", sum(sapply(lo.bal, length))),
                            rep("Polynomial", sum(sapply(ply.bal, length))), rep("Local Linear", sum(sapply(ll.bal, length))))
)
tstat.table$tstat <- abs(tstat.table$Estimate / tstat.table$SE)
tstat.table$Variable <- reorder(tstat.table$Variable, tstat.table$tstat, max)

std.diff.table$Variable <- recode(std.diff.table$Variable, c("'coalvotes' = 'Coalition Votes'; 'yob' = 'Birth Year'; 'comm.donations' = 'Party Donations'; 'incumbent' = 'Incumbent'; 'contracts.0406' = 'Contracts (\\'04-\\'06)'; 'pw.con.0406' = 'Public Works Contracts (\\'04-\\'06)'; 'donations' = 'Total Donations Received'; 'pw.donations' = 'Public Works Donations Received'; 'donor.firms' = 'No. Donor Firms'; 'pw.donor.firms' = 'Percent Public Works Donors'; 'year.opened' = 'Mean Donor Year Founded'; 'commerce' = 'Percent Commerce Donors'; 'manufacture' = 'Percent Manufacturing Donors'; 'financial' = 'Percent Financial Donors'; 'agriculture' = 'Percent Agricultural Donors'; 'cand.uf.sp' = 'State - São Paulo'; 'cand.uf.mg' = 'State - Minas Gerais';  'cand.uf.rs' = 'State - Rio Grande do Sul'; 'superior.edu' = 'Higher Education'; 'occ.pol' = 'Occupation - Politician'; 'individ.donations' = 'Individual Donations'; 'numb.company.recipients' = 'Mean Donor No. Candidate Recipients'; 'party.pmdb' = 'Party - PMDB'; 'party.pfl' = 'Party - PFL'; 'total.company.donations' = 'Mean Donor Total Donations'; 'coalvotes' = 'Coalition Votes'; 'party.pt' = 'Party - PT'; 'party.psdb' = 'Party - PSDB'; 'occ.business' = 'Occupation - Business'; 'cand.uf.rj' = 'State - Rio de Janeiro'; 'cand.uf.ba' = 'State - Bahia'; 'coalseats' = 'Coalition Seats'; 'individual.donors' = 'No. Individual Donors'; 'totalDonations.winners.firm' = 'Mean Donor Donations to Winners'; 'winners.donated.to' = 'Mean Donor No. Winning Recipients'"))

tstat.table$Variable <- recode(tstat.table$Variable, c("'coalvotes' = 'Coalition Votes'; 'yob' = 'Birth Year'; 'comm.donations' = 'Party Donations'; 'incumbent' = 'Incumbent'; 'contracts.0406' = 'Contracts (\\'04-\\'06)'; 'pw.con.0406' = 'Public Works Contracts (\\'04-\\'06)'; 'donations' = 'Total Donations Received'; 'pw.donations' = 'Public Works Donations Received'; 'donor.firms' = 'Donor Firms'; 'pw.donor.firms' = 'Percent Public Works Donors'; 'year.opened' = 'Mean Donor Year Founded'; 'commerce' = 'Percent Commerce Donors'; 'manufacture' = 'Percent Manufacturing Donors'; 'financial' = 'Percent Financial Donors'; 'agriculture' = 'Percent Agricultural Donors'; 'cand.uf.sp' = 'State - São Paulo'; 'cand.uf.mg' = 'State - Minas Gerais';  'cand.uf.rs' = 'State - Rio Grande do Sul'; 'superior.edu' = 'Higher Education'; 'occ.pol' = 'Occupation - Politician'; 'individ.donations' = 'Individual Donations'; 'numb.company.recipients' = 'Mean Donor Candidate Recipients'; 'party.pmdb' = 'Party - PMDB'; 'party.pfl' = 'Party - PFL'; 'total.company.donations' = 'Mean Donor Total Donations'; 'coalvotes' = 'Coalition Votes'; 'party.pt' = 'Party - PT'; 'party.psdb' = 'Party - PSDB'; 'occ.business' = 'Occupation - Business'; 'cand.uf.rj' = 'State - Rio de Janeiro'; 'cand.uf.ba' = 'State - Bahia'; 'coalseats' = 'Coalition Seats'; 'individual.donors' = 'Individual Donors'; 'totalDonations.winners.firm' = 'Mean Donor Donations to Winners'; 'winners.donated.to' = 'Mean Donor Winning Recipients'"))

levels(std.diff.table$Sample) <- c("All", "Public Works", "Public Works, Coalition", "Public Works, PT")

levels(tstat.table$Sample) <- c("All", "Public Works", "Public Works, Coalition", "Public Works, PT")
pdf(file = "figure1.pdf", height = 6, width = 10)
ggplot(tstat.table, aes(x = tstat, y = Variable, shape = Sample, color = Sample)) + geom_point() + geom_vline(xintercept = 2, lty = 2, size = .2) + facet_grid(.~Estimator) + theme_bw() + scale_x_continuous("T Statistic") + scale_color_brewer(palette = "Set1") + labs(title = "Balance Statistics for Federal Deputies") 
dev.off()

```

